apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: flux-system
data:
  MYSQL_HOST: mysql
  MYSQL_USER: "testdb"
  MYSQL_PASSWORD: "12345"
  MYSQL_DATABASE: "demo_db"
